---
micronaut:
  application:
    name: data-access
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
#  security:
#    enabled: true
#    endpoints:
#      login:
#        enabled: true
#      oauth:
#        enabled: true
#    token:
#      jwt:
#        enabled: true
#        signatures:
#          secret:
#            generator:
#              secret: hsLOPhfunrjandirjsnidmfkJNAJDnew

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#end::datasource[]
#tag::jpa[]
jpa:
  default:
    packages-to-scan:
      - 'data.access' # <1>
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true